apiVersion: v1
kind: Secret
metadata:
  name: sublytics-api-secrets
type: Opaque
stringData:
  JWT_ACCESS_TOKEN_SECRET: "replace_me_prod_secret_min_20_chars"
  JWT_ACCESS_TOKEN_TTL_SECONDS: "900"

  STRIPE_SECRET_KEY: "sk_live_replace_me"
  STRIPE_WEBHOOK_SECRET: "whsec_replace_me"
  STRIPE_PRICE_BASIC: "price_replace_me_basic"
  STRIPE_PRICE_PRO: "price_replace_me_pro"

  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET: "sublytics-uploads"
  AWS_ACCESS_KEY_ID: "replace_me"
  AWS_SECRET_ACCESS_KEY: "replace_me"
